const {
    AZURE_AD_CLIENT_ID,
    AZURE_AD_CLIENT_SECRET,
    AZURE_AD_TENANT_ID = "",
    AZURE_AD_POST_LOGOUT_REDIRECT_URI,
    BFF_BASE_URL,
    REACT_APP_ENCRYPTION_KEY,
    REACT_APP_ENCRYPTION_ALGORITHM,
    BASE_URL,
    REACT_APP_ENCRYPTION_IV,
    NEXTAUTH_URL
// eslint-disable-next-line no-undef
} = process.env;

export const ENV = {
    AZURE_AD_CLIENT_ID,
    AZURE_AD_CLIENT_SECRET,
    AZURE_AD_TENANT_ID,
    AZURE_AD_POST_LOGOUT_REDIRECT_URI,
    BFF_BASE_URL,
    REACT_APP_ENCRYPTION_KEY,
    REACT_APP_ENCRYPTION_ALGORITHM,
    REACT_APP_ENCRYPTION_IV,
    NEXTAUTH_URL,
    BASE_URL
};